### ISSUE TITLE
SSL Certificate doesn't exist or is invalid.

### ISSUE THREAD

**Issue by Gamebuster19901** [WiiLink24/Mail-Server#7]
## **Description:**

My Discord bot is no longer receiving Wii mail via the `https://mtw.rc24.xyz/cgi-bin/receive.cgi` endpoint. It appears the SSL certificate for this mail server is either invalid or has been removed.

## **Previous Functionality:**

It was previously possbile to successfully connect and receive/send wii mail via HTTPS.

## **Desired Outcome:**

Even though the Wii doesn't use HTTPS, I request that the SSL certificate for the mail server be restored to allow continued secure communication (HTTPS) with non-wii programs.

## **Stacktrace:**

```
Mar 20 21:28:56 database start.sh[347626]: WARNING: IOException... Skipping mail retrieval
Mar 20 21:28:56 database start.sh[347626]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Mar 20 21:28:56 database start.sh[347626]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
Mar 20 21:28:56 database start.sh[347626]:         at com.gamebuster19901.excite.bot.mail.Mailbox.receive(Mailbox.java:141)
Mar 20 21:28:56 database start.sh[347626]:         at com.gamebuster19901.excite.Main$2.run(Main.java:259)
Mar 20 21:28:56 database start.sh[347626]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.validator.Validator.validate(Validator.java:256)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)
Mar 20 21:28:56 database start.sh[347626]:         ... 25 more
Mar 20 21:28:56 database start.sh[347626]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
Mar 20 21:28:56 database start.sh[347626]:         at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
Mar 20 21:28:56 database start.sh[347626]:         ... 30 more

```

**Comment by noahpistilli** [comment]
Resolved at some point (I apologize for not replying earlier!!!). There was a point where we disabled Cloudflare which removed the SSL certificate. That has now been long rectified.
